=== l3miage-khalili/Java-XML-projects/TP7/src/magasin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0"
           targetNamespace="http://wwww.hejdo.fr/magasin"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:hd="http://wwww.hejdo.fr/magasin"
           elementFormDefault="qualified">
 
    <xs:element name="hejdo" type="hd:Magasin">
        <xs:keyref name="refExist" refer="hd:magRefUnique">
            <xs:selector xpath="hd:expo/hd:reference"/>
            <xs:field xpath="@refProduit"/>
            <xs:field xpath="@refElementProduit"/>
        </xs:keyref>
    </xs:element>
     
    <xs:complexType name="Magasin">
        <xs:sequence>
            <xs:element name="magasin" type="hd:ListeProduits">
                <xs:unique name="magRefUnique">
                    <xs:selector xpath="hd:reference"/>
                    <xs:field xpath="@refProduit"/>
                    <xs:field xpath="@refElementProduit"/>
                </xs:unique>
            </xs:element>
            <xs:element name="expo" type="hd:ListeProduits">
                <xs:unique name="expoRefUnique">
                    <xs:selector xpath="hd:reference"/>
                    <xs:field xpath="@refProduit"/>
                    <xs:field xpath="@refElementProduit"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="ville" type="xs:string"/>
        <xs:attribute name="annee" type="xs:gYear"/>
    </xs:complexType>
     
    <xs:complexType name="ListeProduits">
        <xs:sequence>
            <xs:element name="reference" type="hd:Produit" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
     
    <xs:complexType name="Produit">
        <xs:attribute name="nomProduit" type="xs:string" use="required"/>
        <xs:attribute name="refElementProduit" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Z]"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="refProduit" type="xs:unsignedInt" use="required"/>
        <xs:attribute name="quantite" type="xs:unsignedInt" use="required"/>
    </xs:complexType>  
     
</xs:schema>

=== l3miage-khalili/Java-XML-projects/TP7/src/magasin.xml
<?xml version="1.0" encoding="UTF-8"?>
<hd:hejdo
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:hd='http://wwww.hejdo.fr/magasin'
    xsi:schemaLocation='http://wwww.hejdo.fr/magasin magasin.xsd'>
    <hd:magasin>
        <hd:reference nomProduit="Svalbard" refProduit="1" refElementProduit="A" quantite="12"/>
        <hd:reference nomProduit="Svalbard" refProduit="1" refElementProduit="B" quantite="32"/>
        <hd:reference nomProduit="Mulnörk" refProduit="2" refElementProduit="A" quantite="25"/>
        <hd:reference nomProduit="Traktill" refProduit="3" refElementProduit="A"  quantite="1"/>
    </hd:magasin>
    <hd:expo>
        <hd:reference nomProduit="Svalbard" refProduit="1" refElementProduit="A" quantite="1"/>
        <hd:reference nomProduit="Svalbard" refProduit="1" refElementProduit="B" quantite="4"/>
        <hd:reference nomProduit="Mulnörk" refProduit="2" refElementProduit="A" quantite="2"/>
        <hd:reference nomProduit="Traktill" refProduit="3" refElementProduit="A" quantite="0"/>
    </hd:expo>
</hd:hejdo>
