=== l3miage-khalili/Java-XML-projects/Tux/src/xml/profil.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           targetNamespace="http://myGame/tux"
           xmlns="http://myGame/tux"
           xmlns:dic="http://myGame/tux"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <!-- ici importation du fichier dico.xsd" afin de pouvoir 
        utiliser le type "Mot"
    -->
    
    <xs:include schemaLocation="dico.xsd"/>
    
    <!-- ici declaration du nom et du type d'un element "profil" -->
    
    <xs:element name="profil" type="Profil"/>
    
    <!-- ici definition du type complexe "Profil" de l'element "profil"
        ainsi que declaration du nom et type de ses sous-elements 
        "nom", "avatar", "anniversaire" et "parties"
    -->
    
    <xs:complexType name="Profil">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="avatar" type="Avatar"/>
            <xs:element name="anniversaire" type="xs:date"/>
            <xs:element name="parties" type="Parties"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- ici definition du type simple "Avatar" de l'element "avatar" -->
    
    <xs:simpleType name="Avatar">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z]{1,}.[A-Za-z]{2,4}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- ici definition du type complexe "Parties" de l'element "parties"
        ainsi que declaration du nom et type de son/ses sous-elements
        "partie"
    -->
    
    <xs:complexType name="Parties">
        <xs:sequence>
            <xs:element name="partie" type="Partie" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- ici definition du type complexe "Partie" de l'element "partie"
        ainsi que declaration du nom et type de ses sous-elements
        "temps"(facultatif), "mot" et de ses attributs "date" et "trouvé"(facultatif)
    -->
    
    <xs:complexType name="Partie">
        <xs:sequence>
            <xs:element name="temps" type="xs:double" minOccurs="0" maxOccurs="1"/>
            <xs:element name="mot" type="dic:Mot"/>
        </xs:sequence>
        <xs:attribute name="date" type="xs:date" use="required"/>
        <xs:attribute name="trouvé" type="xs:string"/>
    </xs:complexType>
    
    
</xs:schema>

=== l3miage-khalili/Java-XML-projects/Tux/src/xml/profil_bis.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<ns1:profil
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://myGame/tux'
    xsi:schemaLocation='http://myGame/tux file:/home/k/khalili/NetBeansProjects/FDD_XML/xml-projects/Tux/src/xml/profil.xsd'>
    
    <ns1:nom>Kbg</ns1:nom>
    
    <ns1:avatar>kbgavatar.jpg</ns1:avatar>
    
    <ns1:anniversaire>1900-10-10</ns1:anniversaire>
    
    <ns1:parties>
        <ns1:partie date="2023-10-10" trouvÃ©="88%">
            <ns1:temps>10.0</ns1:temps>
            <ns1:mot niveau="2">Bonjour</ns1:mot>
        </ns1:partie>
    </ns1:parties>

</ns1:profil>
